apiVersion: v1
kind: Service
metadata:
  name: {{ include "mooncake.fullname" . }}-master-service
  labels:
    {{- include "mooncake.labels" (tuple . "master") | nindent 4 }}
spec:
  selector:
    {{- include "mooncake.selectorLabels" (tuple . "master") | nindent 4 }}
  ports:
    - name: general
      port: {{ (default dict .Values.mooncake.master.port).port }}
      targetPort: {{ (default dict .Values.mooncake.master.port).targetPort }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mooncake.fullname" . }}-meta-service
  labels:
      {{- include "mooncake.labels" (tuple . "meta") | nindent 4 }}
spec:
  selector:
    {{- include "mooncake.selectorLabels" (tuple . "meta") | nindent 4 }}
  ports:
    - name: general
      port: {{ (default dict .Values.mooncake.meta.port).port }}
      targetPort: {{ (default dict .Values.mooncake.meta.port).targetPort }}
