# How to use
# echo "GITHUB_TOKEN" > github_token.txt
# docker build --secret id=github_token,src=github_token.txt \
#              -f Dockerfile.moreh -t [image_name] .

# -----------------------
# default base image
ARG COMMON_WORKDIR=/app
ARG BASE_IMAGE="192.168.212.30:1780/cache/moreh-vllm:v0.9.0.0708"
ARG REMOTE_LMCACHE=0

FROM ${BASE_IMAGE} AS base

# Install some basic utilities
RUN apt-get update -q -y && apt-get install -q -y \
    wget perl libstdc++-12-dev tmux protobuf-compiler clang \
    libltdl-dev dkms ethtool quilt bison \
    libnl-route-3-dev pkg-config debhelper libnl-3-200 graphviz m4 libmnl0 libfuse2 \
    autoconf lsof libnl-route-3-200 libusb-1.0-0 tk autotools-dev libnl-3-dev \
    automake flex swig tcl chrpath && \
    rm -rf /var/lib/apt/lists/*

ARG COMMON_WORKDIR
WORKDIR ${COMMON_WORKDIR}

# -----------------------
# install OFED & UCX
FROM base AS install_basic

RUN wget http://www.mellanox.com/downloads/ofed/MLNX_OFED-24.10-2.1.8.0/MLNX_OFED_LINUX-24.10-2.1.8.0-ubuntu22.04-x86_64.tgz \
    && tar -xzvf MLNX_OFED_LINUX-24.10-2.1.8.0-ubuntu22.04-x86_64.tgz \
    && cd MLNX_OFED_LINUX-24.10-2.1.8.0-ubuntu22.04-x86_64 \
    && ./mlnxofedinstall --force --without-fw-update --user-space-only \
            --basic --with-perftest \
    && cd .. && rm -rf MLNX_OFED_LINUX-24.10-2.1.8.0-ubuntu22.04-x86_64*

RUN wget https://github.com/openucx/ucx/releases/download/v1.18.0/ucx-1.18.0.tar.gz \
    && tar -xvf ucx-1.18.0.tar.gz \
    && cd ucx-1.18.0 \
    && ./configure --enable-shared --disable-static --disable-doxygen-doc \
       --enable-optimizations --enable-devel-headers --enable-mt \
       --with-rocm=/opt/rocm --with-mlx5 --prefix /usr/local\
    && make -j && make install \
    && cd .. && rm -rf ucx-1.18.0*

# -----------------------
#  fetch lmcache
FROM base AS fetch_0
ONBUILD COPY ./ LMCache/
FROM base AS fetch_1
ARG LMCACHE_REPO="https://github.com/LMCache/LMCache.git"
ARG LMCACHE_BRANCH="v0.3.7"
ONBUILD RUN git clone --branch ${LMCACHE_BRANCH} --single-branch "${LMCACHE_REPO}"
FROM fetch_${REMOTE_LMCACHE} AS fetch_lmcache

# ----------------------
# build lmcache
FROM fetch_lmcache AS build_lmcache
ARG COMMON_WORKDIR

RUN cd LMCache && PYTORCH_ROCM_ARCH="gfx90a;gfx942" \
    TORCH_DONT_CHECK_COMPILER_ABI=1 \
    CXX=hipcc \
    BUILD_WITH_HIP=1 \
    python3 setup.py bdist_wheel --dist-dir=dist

# -----------------------
#  build nixl
FROM install_basic AS build_nixl
ARG COMMON_WORKDIR
ARG NIXL_REPO="github.com/moreh-dev/nixl.git"

RUN pip install build

RUN --mount=type=secret,id=github_token \
    GITHUB_TOKEN=$(cat /run/secrets/github_token) \
    && git clone --branch "0.3.0-rocm" --single-branch "https://${GITHUB_TOKEN}@${NIXL_REPO}" \
    && cd nixl && echo "$PATH" && python -m build --wheel

FROM scratch AS export_build
ARG COMMON_WORKDIR
COPY --from=build_lmcache   ${COMMON_WORKDIR}/LMCache/dist/*.whl /
COPY --from=build_nixl      ${COMMON_WORKDIR}/nixl/dist/*.whl /

# -----------------------
# Final image
FROM install_basic AS final

# Install lmcache
RUN --mount=type=bind,from=export_build,src=/,target=/install \
    cd /install \
    && pip install *.whl
# add mooncake, infinistore for sharing
RUN pip install mooncake-transfer-engine infinistore

ARG COMMON_WORKDIR

ENV LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib/python3.12/dist-packages/torch/lib
WORKDIR ${COMMON_WORKDIR}
CMD ["/bin/bash"]

