apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "lmcache.fullname" . }}-servicemonitor
  labels:
    {{- include "lmcache.labels" . | nindent 4 }}
spec:
  endpoints:
    - honorLabels: false
      interval: 10s
      path: /metrics
      port: general
  namespaceSelector:
    matchNames:
      - {{.Release.Namespace}}
  selector:
    matchLabels:
      {{- include "lmcache.selectorLabels" . | nindent 6 }}
