apiVersion: v1
kind: Service
metadata:
  name: {{ include "lmcache.fullname" . }}-service
  labels:
    {{- include "lmcache.labels" . | nindent 4 }}
spec:
  selector:
   {{- include "lmcache.selectorLabels" . | nindent 4 }}
  ports:
    - name: general
      port: {{ (default dict .Values.lmcache.port).port | default 8000 }}
      targetPort: {{ (default dict .Values.lmcache.port).targetPort | default 8000 }}
